### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by graperaisin1** [lukasgit/flutter_contacts#192]
Getting this error when running  `contacts_service: ^0.4.6` on iOS:

```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file contacts_service/SwiftContactsServicePlugin.swift, line 31
Lost connection to device.
Exited (sigterm)
```

The line in question:
```
public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        switch call.method {
        case "getContacts":
            let arguments = call.arguments as! [String:Any]
            result(getContacts(query: (arguments["query"] as? String), withThumbnails: arguments["withThumbnails"] as! Bool,
                               // ******** Line 31 below:  ********
                               photoHighResolution: arguments["photoHighResolution"] as! Bool, phoneQuery:  false, orderByGivenName: arguments["orderByGivenName"] as! Bool,
                               localizedLabels: arguments["iOSLocalizedLabels"] as! Bool ))
        case "getContactsForPhone":
```

`flutter doctor`:

```
✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.2)
```

Can anyone advise?

**Comment by lukasgit** [comment]
@graperaisin1 Please use the latest version `contacts_service: ^0.6.1`

**Comment by GotaloveCode** [comment]
contacts_service/SwiftContactsServicePlugin.swift:16: Fatal error: Unexpectedly found nil while unwrapping an Optional value on build using contacts_service: ^0.6.3

**Comment by usama-sherazi** [comment]
he Flutter app crashes immediately on launch
contacts_service/ContactsServicePlugin.swift:16:
Fatal error: Unexpectedly found nil while unwrapping an Optional value

contacts_service:
  git:
    url: https://github.com/hkhere/flutter_contacts.git
    ref: master
